### PR TITLE
fix jwt claims

### PR DESCRIPTION
**Pull request by hesamhamdarsi**

### CODE REVIEW

**Comment by 1995parham** [comment]
Hi Hessam jan, the following was wrong:

```go
token.Claims.(*jwt.RegisteredClaims)
```

Because we need to use `ParseWithClaims` for using our custom claims. I fixed this code in our second meeting about JWT.

**Comment by hesamhamdarsi** [comment]
before using "ParseWithClaims" and with "Parse" that was right, but as I've checked, after creating token using "&jwt.RegisteredClaims{}" , we don't get the error of "value of type jwt.Claims" anymore and the following works correctly:
token.Claims.(*jwt.RegisteredClaims)

**Comment by 1995parham** [comment]
Oh, Let me check it

**Comment by 1995parham** [comment]
Thanks, @hesamhamdarsi jan. I didn't know that, by using this, we can remove the redundant variable definition for `claims` #2

**Pull request merged**
